# data1 = pd.read_csv('flow_handoff.csv', delimiter=',')
# data2 = pd.read_csv('mpstat.csv', delimiter=',')
# data_outer = pd.merge(data1, data2, on='Time', how='outer')
# print(len(data_outer))
# dup = data_outer.drop_duplicates(subset=['Time', 'CPU'], keep='last')
# print(len(dup))
# dup.to_csv('combined_data.csv', index=False)
# df1 = pd.read_csv('combined_data.csv', delimiter=",")
# df2 = pd.read_csv('vmstat.csv', delimiter=",")
# data_merge = pd.merge(df1, df2, on="Time",how="outer")
# print(len(data_merge))
# print(data_merge.head(20))
# data_merge.to_csv('combined_data1.csv', index=False)
# df5 = pd.read_csv('combined_data1.csv')
# df3 = pd.read_csv('debug_handoff.csv')
# df4 = pd.merge(df5, df3 , on='Time', how='outer')
# df6 = df4.drop_duplicates(subset=['Time','CPU', 'name'], keep = 'last')
# df6.to_csv('combined_data2.csv', index=False)

